### PR TITLE
Added FullScreenModeTrigger

### PR DESCRIPTION
**Pull request by marcominerva**
A trigger that is activated when the app is in full screen mode.

### CODE REVIEW

**Comment by dotMorten** [comment]
I like this pull-request! Great idea.
Just a few comments:
- Sync with latest master so it will auto-merge (sorry for the slow response - my bad)
- Remove changes to files not related to the trigger (project updates etc)
- Don't use dependency properties for properties (it was a mistake and is to be removed from the other triggers that use it)

**Comment by marcominerva** [comment]
Done :-) I hope I have done the sync with latest master correctly. Otherwise, I think I'll make another branch and re-add the FullScreenModeTrigger, to avoid confusion. Keep me posted :-)

**Comment by dotMorten** [comment]
Yeah something went wrong in your merge. All the things that were already changed is showing up as changed again. A new branch is probably needed.
Looking at the fork, it doesn't show an arrow indicating the merge from this repo to yours: https://github.com/dotMorten/WindowsStateTriggers/network

**Comment by marcominerva** [comment]
OK, I will make another branch and then pull request again!

**Pull request closed without merging**
