### PR TITLE
Add IsNullOrEmptyStateTrigger

### LINKED ISSUE #4: Null or empty trigger
Add a trigger for when something is null, or a collection/string is empty.

### PR DESCRIPTION
**Pull request by robertos**
Let's kick off the code review for this :)

This new trigger supports null objects, empty strings, and empty collections (ICollection / IEnumerable).
It also listens to change notifications if available (INotifyCollectionChanged, IObservableVector<T>, IObservableMap<K,V>)

Fixes #4

### CODE REVIEW

**Comment by dotMorten** [comment]
I just love extra code and premature optimizations ;-)

Anyway awesome work. Looks good but won't merge. Could you merge again?.

**Comment by robertos** [comment]
Sure, I'll merge the Regex change in. Do you want me to rebase as well?

**Comment by dotMorten** [comment]
Merge is fine

**Comment by robertos** [comment]
Ready to go :+1:

**Pull request merged**
