### PR TITLE
Make NotEqualStateTrigger implement ITriggerValue.

### PR DESCRIPTION
**Pull request by peterbozso**
The title sums it up. Now NotEqualStateTrigger can be contained by CompositeStateTrigger.

### CODE REVIEW

**Comment by tomzorz** [comment]
Just ran into this as well :) +1 for the PR

**Comment by peterbozso** [comment]
@dotMorten ping!

**Comment by dotMorten** [comment]
Awesome! Thanks!

**Comment by tibitoth** [comment]
Am I miss something? Closed but not merged?

**Comment by dotMorten** [comment]
My bad 😀

**Comment by peterbozso** [comment]
Thanks both of you! :)

**Comment by peterbozso** [comment]
@dotMorten Could you please update the NuGet package with this fix?

**Comment by peterbozso** [comment]
ping @dotMorten

**Comment by peterbozso** [comment]
ping @dotMorten The last NuGet version is still from February 2.

**Comment by maxkatz6** [comment]
@dotMorten ?

**Pull request merged**
